c_stdlib:                  # [win and not arm64]
- m2w64-sysroot            # [win and not arm64]
c_stdlib_version:
- '12.3'                   # [osx]
- '12'                     # [win and not arm64]
c_compiler:                # [win and not arm64]
- gcc                      # [win and not arm64]
c_compiler_version:        # [win and not arm64]
- 14                       # [win and not arm64]
cxx_compiler:              # [win and not arm64]
- gxx                      # [win and not arm64]
cxx_compiler_version:      # [win and not arm64]
- 14                       # [win and not arm64]
