c_stdlib:                  # [win]
- m2w64-sysroot            # [win]
c_stdlib_version:
- '2.17'                   # [linux]
- '11.0'                   # [osx and x86_64]
- '12'                     # [win]
c_compiler:                # [win]
- gcc                      # [win]
c_compiler_version:
- 12                       # [ppc64le]
- 13                       # [win]
cxx_compiler:              # [win]
- gxx                      # [win]
cxx_compiler_version:
- 12                       # [ppc64le]
- 13                       # [win]
