c_stdlib:                  # [win]
- m2w64-sysroot            # [win]
c_stdlib_version:
- '2.17'                   # [linux and not ppc64le]
- '2.28'                   # [linux and ppc64le]
- '11.0'                   # [osx and x86_64]
- '12'                     # [win]
c_compiler:                # [win]
- gcc                      # [win]
c_compiler_version:        # [win]
- 13                       # [win]
cxx_compiler:              # [win]
- gxx                      # [win]
cxx_compiler_version:      # [win]
- 13                       # [win]
docker_image:                                       # [linux and ppc64le]
  - quay.io/condaforge/linux-anvil-alma-ppc64le:8   # [linux and ppc64le]
